name: 'Project Setup'

on:
  workflow_dispatch:
    inputs:
      user_repo:
        description: "Repository with user project code"
        required: true
        default: "project-template"

      user_cache:
        description: "Commit SHA of project code"
        required: false

env:
  TEST_REPO: "project-tests"
  TEST_PATH: "project-tests"
  USER_PATH: "project-main"

jobs:
  results:
    runs-on: ubuntu-latest
    name: Project Setup
 
    steps:
      - name: Get Test Commit SHA
        uses: actions/github-script@v6
        env:
          REPO_NAME: "${{ env.TEST_REPO }}"
        with:
          script: |
            const params = {
              owner: context.repo.owner,
              repo: process.env.REPO_NAME,
              per_page: 1
            };

            const result = await github.rest.repos.listCommits(params);

            if (result.status === 200 && result.data.length === 1) {
              const sha = result.data[0].sha;
              core.info(`sha: ${sha}`);
              return sha;
            }

            core.info(`params: ${JSON.stringify(params)}`);
            core.info(`result: ${JSON.stringify(result)}`);
            core.setFailed(`Unable to find commit SHA for: ${process.env.REPO_NAME}`);

      - name: Get Code Commit SHA
        uses: actions/github-script@v6
        if: ${{ inputs.user_cache == '' }}
        env:
          REPO_NAME: "${{ inputs.user_repo }}"
        with:
          script: |
            const params = {
              owner: context.repo.owner,
              repo: process.env.REPO_NAME,
              per_page: 1
            };

            const result = await github.rest.repos.listCommits(params);

            if (result.status === 200 && result.data.length === 1) {
              const sha = result.data[0].sha;
              core.info(`sha: ${sha}`);
              return sha;
            }

            core.info(`params: ${JSON.stringify(params)}`);
            core.info(`result: ${JSON.stringify(result)}`);
            core.setFailed(`Unable to find commit SHA for: ${process.env.REPO_NAME}`);


      # - name: Check Results
      #   id: check-results
      #   uses: usf-cs272-fall2022/action-project-setup@main
      #   with:
      #     user_repo:  "${{ inputs.user_repo }}"
      #     test_repo:  "${{ inputs.test_repo }}"
      #     user_cache: "${{ inputs.user_cache }}"
      #     test_cache: "${{ inputs.test_cache }}"
      #     user_path:  "${{ inputs.user_path }}"
      #     test_path:  "${{ inputs.test_path }}"